---
settings:
  name: NetApp data services
  platform: cloud
  search: console-alerts, storage-management-s3-storage, console-automation, storage-management-azure-netapp-files,
    data-services-backup-recovery, storage-management-blob-storage, data-services-data-classification,
    storage-management-cloud-volumes-ontap, storage-management-google-cloud-netapp-volumes,
    data-services-data-classification, data-services-copy-sync, active-iq, console-licenses-subscriptions,
    data-services-disaster-recovery, storage-management-e-series, console-lifecycle-planning,
    storage-management-fsx-ontap, storage-management-google-cloud-storage, storage-management-ontap-onprem,
    data-services-ransomware-resilience, console-relnotes,data-services-replication,
    console-setup-admin, console-software-updates, storage-management-storagegrid,
    data-services-cloud-tiering, console-volume-caching, workload-setup-admin,workload-fsx-ontap,workload-databases,workload-genai,workload-vmware,
    keystone-staas
  internal:
    pdf_enabled: false
    lipi_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: false
    lipi_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Console NetApp
    url: "../console-setup-admin/index.html"
  - title: Gestione dello storage
    url: "../storage-management-family/index.html"
  - title: Note di rilascio
    url: "../console-relnotes/index.html"
  - title: Backup e ripristino
    url: "../data-services-backup-recovery/index.html"
  - title: Cloud Tiering
    url: "../data-services-cloud-tiering/index.html"
  - title: Copia e sincronizza
    url: "../data-services-copy-sync/index.html"
  - title: Classificazione dei dati
    url: "../data-services-data-classification/index.html"
  - title: Ripristino dopo un disastro
    url: "../data-services-disaster-recovery/index.html"
  - title: Resilienza al ransomware
    url: "../data-services-ransomware-resilience/index.html"
  - title: Replicazione
    url: "../data-services-replication/index.html"
  - title: Caching del volume
    url: "../data-services-volume-caching/index.html"
  - title: Carichi di lavoro
    url: "../workload-family"
